GET http://localhost:8082/log
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjczNDU3MzUsImlhdCI6MTcyNzMzODUzNSwiaWQiOjEsInVzZXJuYW1lIjoiaWthbmlrYW4ifQ.a3MmsV0GkXAbM1b_09ImE_kd9i3YuGv0nTjS8GCSQrA