PUT http://localhost:8082/users/password/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjg2NDc2NTEsImlhdCI6MTcyODY0MDQ1MSwiaWQiOjEsInVzZXJuYW1lIjoiaWthbmlrYW4ifQ.r16XcmdxR4M2MEis-3CndDVTa-C8V3slxD3BQHvRcMw
Content-Type: application/json

{
    "password": "ikanikan"
}